linterAfterTests: false

tests:
  go:
    coverage: 'total:.*?[-+]?((?:\d*\.\d+|\d+)%)'
    cmds:
      - 'go test -coverprofile=cover.out ./...'
      - 'go tool cover -func=cover.out'

ignorePatterns:
  - 'testdata/**'
  - 'sdk/**'
